version: 0.0
os: linux
files:
  - source: /site
    destination: /var/www/html/dotnetapp
hooks:
  BeforeInstall:
  # - location: scripts/install_dependencies.sh
  #   timeout: 300
  #   runas: root
  AfterInstall:
  #  - location: scripts/change_permissions.sh
  #    timeout: 300
  #    runas: root
  ApplicationStart:
    - location: ./installApp.sh
      timeout: 300
  ApplicationStop:
  #   - location: scripts/stop_server.sh
  #    timeout: 300
  #    runas: root