version: 0.2
phases:
    pre_build:
        commands:
        - echo Restore started on `date`
        - ls -ltr
        - dotnet restore dotnetapp.csproj
    build:
        commands:
        - echo Build started on `date`
        - dotnet publish -c release -o ./build_output dotnetapp.csproj
