version: 0.2
phases:
    build:
        commands:
        - echo Restore started on `date`
        - ls -ltr
        - dotnet restore dotnetapp.csproj
        - echo Build started on `date`
        - dotnet build dotnetapp.csproj
        - dotnet publish -c release dotnetapp.csproj -o site
artifacts:
    files:
    - site/**/*
    - aws-windows-deployment-manifest.json
    - appspec.yml
    - installApp.sh